[project]
name = "chai-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
